bootstrap/config/routes.rb
Rails.application.routes.draw do
  resources :students_books
  resources :students
  resources :books
  get 'user/index'
  root 'user#index'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "/"
end

bootstrap/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

bootstrap/app/models/book.rb
class Book < ApplicationRecord
end

bootstrap/app/models/student.rb
class Student < ApplicationRecord
end

bootstrap/app/models/students_book.rb
class StudentsBook < ApplicationRecord
end

bootstrap/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bootstrap/app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
  end
end

bootstrap/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_id, :book_name, :book_author)
    end
end

bootstrap/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

bootstrap/app/controllers/students_books_controller.rb
class StudentsBooksController < ApplicationController
  before_action :set_students_book, only: %i[ show edit update destroy ]

  # GET /students_books or /students_books.json
  def index
    @students_books = StudentsBook.all
  end

  # GET /students_books/1 or /students_books/1.json
  def show
  end

  # GET /students_books/new
  def new
    @students_book = StudentsBook.new
  end

  # GET /students_books/1/edit
  def edit
  end

  # POST /students_books or /students_books.json
  def create
    @students_book = StudentsBook.new(students_book_params)

    respond_to do |format|
      if @students_book.save
        format.html { redirect_to students_book_url(@students_book), notice: "Students book was successfully created." }
        format.json { render :show, status: :created, location: @students_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @students_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students_books/1 or /students_books/1.json
  def update
    respond_to do |format|
      if @students_book.update(students_book_params)
        format.html { redirect_to students_book_url(@students_book), notice: "Students book was successfully updated." }
        format.json { render :show, status: :ok, location: @students_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @students_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students_books/1 or /students_books/1.json
  def destroy
    @students_book.destroy

    respond_to do |format|
      format.html { redirect_to students_books_url, notice: "Students book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students_book
      @students_book = StudentsBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def students_book_params
      params.require(:students_book).permit(:Ma_HS, :Ten_HS, :Lop, :Ma_Sach, :Ten_Sach, :Ten_TacGia, :Tu_Sach, :So_BM, :NgayMuon, :NgayTra, :So_Ngay)
    end
end

bootstrap/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:student_id, :student_name)
    end
end

bootstrap/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

bootstrap/app/helpers/application_helper.rb
module ApplicationHelper
end

bootstrap/app/helpers/book_helper.rb
module BookHelper
end

bootstrap/app/helpers/books_helper.rb
module BooksHelper
end

bootstrap/app/helpers/home_helper.rb
module HomeHelper
end

bootstrap/app/helpers/students_books_helper.rb
module StudentsBooksHelper
end

bootstrap/app/helpers/students_helper.rb
module StudentsHelper
end

bootstrap/app/helpers/user_helper.rb
module UserHelper
end

bootstrap/app/views/book/index.html.erb
<h1>Book#index</h1>
<p>Find me in app/views/book/index.html.erb</p>

bootstrap/app/views/books/_book.html.erb
<tr>
  <th scope="row"><%= index %></th>
  <td><%= book.book_id %></td>
  <td><%= book.book_name %></td>
  <td><%= book.book_author %></td>
</tr>

bootstrap/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :book_name, style: "display: block" %>
    <%= form.text_field :book_name %>
  </div>

  <div>
    <%= form.label :book_author, style: "display: block" %>
    <%= form.text_field :book_author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bootstrap/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

bootstrap/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Author</th>
    </tr>
    </thead>
    <tbody>
    <% i_253 = 1 %>
  <% @books.each do |book_253| %>
    <%= render :partial => 'books/book', :locals => {:index => i_253, :book => book_253}%>
    <% i_253 += 1 %>
  <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New book", new_book_path %>

bootstrap/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

bootstrap/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

bootstrap/app/views/home/index.html.erb
<div class="w-50 mt-3 ml-auto mr-auto">
</div>

bootstrap/app/views/layouts/_footer.html.erb
<footer
  class="text-center text-lg-start text-white"
  style="background-color: #45526e"
>
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">
            Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer
            content. Lorem ipsum dolor sit amet, consectetur adipisicing
            elit.
          </p>
        </div>
        <!-- Grid column -->

        <hr class="w-100 clearfix d-md-none" />

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
          <p>
            <a class="text-white">MDBootstrap</a>
          </p>
          <p>
            <a class="text-white">MDWordPress</a>
          </p>
          <p>
            <a class="text-white">BrandFlow</a>
          </p>
          <p>
            <a class="text-white">Bootstrap Angular</a>
          </p>
        </div>
        <!-- Grid column -->

        <hr class="w-100 clearfix d-md-none" />

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">
            Useful links
          </h6>
          <p>
            <a class="text-white">Your Account</a>
          </p>
          <p>
            <a class="text-white">Become an Affiliate</a>
          </p>
          <p>
            <a class="text-white">Shipping Rates</a>
          </p>
          <p>
            <a class="text-white">Help</a>
          </p>
        </div>

        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none" />

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
          <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
          <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->

    <hr class="my-3">

    <!-- Section: Copyright -->
    <section class="p-3 pt-0">
      <div class="row d-flex align-items-center">
        <!-- Grid column -->
        <div class="col-md-7 col-lg-8 text-center text-md-start">
          <!-- Copyright -->
          <div class="p-3">
            © 2020 Copyright:
            <a class="text-white" href="https://fb.me/binhhothai204"
            >MDBootstrap.com</a
            >
          </div>
          <!-- Copyright -->
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
          <!-- Facebook -->
          <a
            class="btn btn-outline-light btn-floating m-1 text-white"
            role="button"
          ><i class="fab fa-facebook-f"></i
          ></a>

          <!-- Twitter -->
          <a
            class="btn btn-outline-light btn-floating m-1 text-white"
            role="button"
          ><i class="fab fa-twitter"></i
          ></a>

          <!-- Google -->
          <a
            class="btn btn-outline-light btn-floating m-1 text-white"
            role="button"
          ><i class="fab fa-google"></i
          ></a>

          <!-- Instagram -->
          <a
            class="btn btn-outline-light btn-floating m-1 text-white"
            role="button"
          ><i class="fab fa-instagram"></i
          ></a>
        </div>
        <!-- Grid column -->
      </div>
    </section>
    <!-- Section: Copyright -->
  </div>
  <!-- Grid container -->
</footer>

bootstrap/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Book Care', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Manager', students_books_url, class: "nav-link" %>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

bootstrap/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Bootstrap demo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!--  link css js and fontawaresome-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!--  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container min-vh-100 mt-2">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

bootstrap/app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :student_name, style: "display: block" %>
    <%= form.text_field :student_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bootstrap/app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Student:</strong>
    <%= student.student_id %>
  </p>

  <p>
    <strong>Student name:</strong>
    <%= student.student_name %>
  </p>

</div>

bootstrap/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

bootstrap/app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

bootstrap/app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

bootstrap/app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

bootstrap/app/views/students_books/_form.html.erb
<%= form_with(model: students_book) do |form| %>
  <% if students_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(students_book.errors.count, "error") %> prohibited this students_book from being saved:</h2>

      <ul>
        <% students_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Ma_HS, style: "display: block" %>
    <%= form.text_field :Ma_HS %>
  </div>

  <div>
    <%= form.label :Ten_HS, style: "display: block" %>
    <%= form.text_field :Ten_HS %>
  </div>

  <div>
    <%= form.label :Lop, style: "display: block" %>
    <%= form.text_field :Lop %>
  </div>

  <div>
    <%= form.label :Ma_Sach, style: "display: block" %>
    <%= form.text_field :Ma_Sach %>
  </div>

  <div>
    <%= form.label :Ten_Sach, style: "display: block" %>
    <%= form.text_field :Ten_Sach %>
  </div>

  <div>
    <%= form.label :Ten_TacGia, style: "display: block" %>
    <%= form.text_field :Ten_TacGia %>
  </div>

  <div>
    <%= form.label :Tu_Sach, style: "display: block" %>
    <%= form.text_field :Tu_Sach %>
  </div>

  <div>
    <%= form.label :So_BM, style: "display: block" %>
    <%= form.text_field :So_BM %>
  </div>

  <div>
    <%= form.label :NgayMuon, style: "display: block" %>
    <%= form.datetime_field :NgayMuon %>
  </div>

  <div>
    <%= form.label :NgayTra, style: "display: block" %>
    <%= form.datetime_field :NgayTra %>
  </div>

  <div>
    <%= form.label :So_Ngay, style: "display: block" %>
    <%= form.number_field :So_Ngay %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

bootstrap/app/views/students_books/_students_book.html.erb
<tr>
  <th scope="row"><%= index %></th>
  <td><%= students_book_253.Ma_HS %></td>
  <td><%= students_book_253.Ten_HS %></td>
  <td><%= students_book_253.Lop %></td>
  <td><%= students_book_253.Ma_Sach %></td>
  <td><%= students_book_253.Ten_Sach %></td>
  <td><%= students_book_253.Ten_TacGia %></td>
  <td><%= students_book_253.Tu_Sach %></td>
  <td><%= students_book_253.So_BM %></td>
  <td><%= students_book_253.NgayMuon %></td>
  <td><%= students_book_253.NgayTra %></td>
  <td><%= students_book_253.So_Ngay %></td>
</tr>

bootstrap/app/views/students_books/edit.html.erb
<h1>Editing students book</h1>

<%= render "form", students_book: @students_book %>

<br>

<div>
  <%= link_to "Show this students book", @students_book %> |
  <%= link_to "Back to students books", students_books_path %>
</div>

bootstrap/app/views/students_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students books</h1>

<div id="students_books">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ma HS</th>
      <th scope="col">Ten HS</th>
      <th scope="col">Lop</th>
      <th scope="col">Ma Sach</th>
      <th scope="col">Ten Sach</th>
      <th scope="col">Tac Gia</th>
      <th scope="col">Tu Sach</th>
      <th scope="col">So BM</th>
      <th scope="col">Ngay Muon</th>
      <th scope="col">Ngay Tra</th>
      <th scope="col">So Ngay</th>
    </tr>
    </thead>
    <tbody>
    <% i_253 = 1 %>
    <% @students_books.each do |students_book_253| %>
      <%= render :partial => 'students_books/students_book', :locals => {:index => i_253, :students_book_253 => students_book_253}%>
      <% i_253 += 1 %>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New students book", new_students_book_path %>

bootstrap/app/views/students_books/new.html.erb
<h1>New students book</h1>

<%= render "form", students_book: @students_book %>

<br>

<div>
  <%= link_to "Back to students books", students_books_path %>
</div>

bootstrap/app/views/students_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @students_book %>

<div>
  <%= link_to "Edit this students book", edit_students_book_path(@students_book) %> |
  <%= link_to "Back to students books", students_books_path %>

  <%= button_to "Destroy this students book", @students_book, method: :delete %>
</div>

bootstrap/app/views/user/index.html.erb
<h1>
  Quản lý học sinh mượn sách
</h1>